
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: sunrise
  password: sunrise123

development:
  <<: *default
  database: codevarma_v1_development

test:
  <<: *default
  database: codevarma_v1_test

production:
  <<: *default
  database: codevarma_production
  username: codevarma
  password: <%= ENV['CODEVARMA_DATABASE_PASSWORD'] %>
